<?php
$arr_content = $this->arrContentList;
$category_detail = $this->arrCategoryDetail;
$arr_keyword = $this->arrKeywordList;
?>

<div class="content">
    <div id="adindexcenter" class="adbox" style="margin-bottom:20px;">
        <img src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/640x60.png'; ?>">
    </div>
    <div class="breadcrumbs-box">
    <h1><?php echo $category_detail['cate_name'] ?></h1>
    </div>


    <div class="listview clearfix">
        <ul>
            <?php for ($i = 0; $i < 2; $i++):
                if(isset($arr_content[$i]) && $arr_content[$i]):
                ?>

                <li class="listitem clearfix">
                    <a class="title"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content[$i]['cont_slug'], 'contentId' => $arr_content[$i]['cont_id']]) ?>">
                        <?php echo $arr_content[$i]['cont_title'] ?>
                    </a>
                    <a class="thumb"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content[$i]['cont_slug'], 'contentId' => $arr_content[$i]['cont_id']]) ?>">
                        <img src="<?php echo $arr_content[$i]['cont_main_image'] ?>"
                             alt="<?php echo $arr_content[$i]['cont_title'] ?>">
                    </a>
                    <div class="desc"><?php echo $arr_content[$i]['cont_description'] ?></div>
                </li>
            <?php endif;
            endfor;
            ?>
        </ul>
    </div>
    <div id="adsinfeed" class="adbox" style="margin-bottom:20px">

    </div>
    <div class="listview clearfix">
        <ul>
            <?php for ($i = 2; $i < 10; $i++):
                if(isset($arr_content[$i]) && $arr_content[$i]):
                ?>
                <li class="listitem clearfix">
                    <a class="title"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content[$i]['cont_slug'], 'contentId' => $arr_content[$i]['cont_id']]) ?>">
                        <?php echo $arr_content[$i]['cont_title'] ?>
                    </a>
                    <a class="thumb"
                       href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content[$i]['cont_slug'], 'contentId' => $arr_content[$i]['cont_id']]) ?>">
                        <img src="<?php echo $arr_content[$i]['cont_main_image'] ?>"
                             alt="<?php echo $arr_content[$i]['cont_title'] ?>">
                    </a>
                    <div class="desc"><?php echo $arr_content[$i]['cont_description'] ?></div>
                </li>
            <?php endif; endfor; ?>
        </ul>
    </div>
    <div class="pagination-container">
        <ul class="pagination">
            <?php echo $this->paging; ?>
        </ul>
    </div>
</div>