<div class=td-crumb-container>
    <div class=entry-crumbs>
        <span>
            <a title="Home" class=entry-crumb itemprop=url href="<?php echo $this->serverUrl() . $this->Url('home') ?>">
                <span itemprop=title><i class="fa fa-home"></i> Home</span>
            </a>
        </span>
        <i class="td-icon-right td-bread-sep td-bred-no-url-last"></i>
        <span class=td-bred-no-url-last>
            <meta itemprop=title content="<?php echo $this->arrCategoryDetail['cate_name']; ?>">
            <meta itemprop=url content="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' =>  $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id']]) ?>">
            <?php echo $this->arrCategoryDetail['cate_name']; ?>
        </span>
    </div>
</div>

<h1 class="entry-title td-page-title"><?php echo $this->arrCategoryDetail['cate_name']; ?></h1>
<div class=td-ss-main-content>
    <?php foreach ($this->arrContentList as $arr_content): ?>
        <div class="td_module_10 td_module_wrap td-animation-stack">
            <div class=td-module-thumb>
                <a rel="nofollow" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
                   rel=bookmark title="<?php echo $arr_content['cont_title']; ?>">
                    <img width=218 height=150 class=entry-thumb src="<?php echo $arr_content['cont_resize_image'] ?>"
                         alt="" title="<?php echo $arr_content['cont_title']; ?>"/>
                </a>
            </div>
            <div class=item-details>
                <h3 class="entry-title td-module-title">
                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>"
                       rel=bookmark title="<?php echo $arr_content['cont_title']; ?>">
                        <?php echo $arr_content['cont_title']; ?>
                    </a>
                </h3>
                <div class=td-module-meta-info>
                    <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' =>  $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id']]) ?>" class=td-post-category><?php echo $this->arrCategoryDetail['cate_name']; ?></a>
                    <span class=td-post-date><time class="entry-date updated td-module-date"
                                                   datetime=""><?php echo date("d-m-Y", $arr_content['created_date']); ?></time></span>
                </div>
                <div class=td-excerpt>
                    <?php echo (strlen($arr_content['cont_description']) < 100) ? $arr_content['cont_description'] : mb_substr($arr_content['cont_description'], 0, 100, 'UTF-8') . '...'; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<div class="page-nav td-pb-padding-side">
    <?php echo $this->paging; ?>
</div>
