<div class="vc_row wpb_row td-pb-row">
    <div class="wpb_column vc_column_container td-pb-span12">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td_block_wrap td_block_big_grid_1 td-grid-style-1 td-hover-1 td-pb-border-top">
                    <div class="td_block_inner">
                        <div class="td-big-grid-wrapper">
                            <div class="td_module_mx5 td-animation-stack td-big-grid-post-0 td-big-grid-post td-big-thumb">
                                <div class="td-module-thumb">
                                    <a rel="nofollow" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_WORLD][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_WORLD][0]['cont_id']]) ?>"
                                        rel="bookmark" title="<?php echo $this->arrContent[\My\General::CATEGORY_WORLD][0]['cont_title'] ?>">
                                        <img width="534" height="462" class="entry-thumb td-animation-stack-type0-2"
                                                src="<?php echo $this->arrContent[\My\General::CATEGORY_WORLD][0]['cont_main_image'] ?>"
                                            alt="<?php echo $this->arrContent[\My\General::CATEGORY_WORLD][0]['cont_title'] ?>"
                                            title="<?php echo $this->arrContent[\My\General::CATEGORY_WORLD][0]['cont_title'] ?>">
                                    </a>
                                </div>
                                <div class="td-meta-info-container">
                                    <div class="td-meta-align">
                                        <div class="td-big-grid-meta">
                                            <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategory[\My\General::CATEGORY_WORLD]['cate_slug'], 'cateId' => $this->arrCategory[\My\General::CATEGORY_WORLD]['cate_id']]) ?>"
                                               class="td-post-category">
                                                <?php echo $this->arrCategory[\My\General::CATEGORY_WORLD]['cate_name'] ?>
                                            </a>
                                            <h3 class="entry-title td-module-title">
                                                <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_WORLD][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_WORLD][0]['cont_id']]) ?>"
                                                    rel="bookmark"
                                                    title="<?php echo $this->arrContent[\My\General::CATEGORY_WORLD][0]['cont_title'] ?>">
                                                    <?php echo $this->arrContent[\My\General::CATEGORY_WORLD][0]['cont_title'] ?>
                                                </a>
                                            </h3>
                                        </div>
                                        <div class="td-module-meta-info">
<!--                                            <span class="td-post-date">-->
<!--                                                <time class="entry-date updated td-module-date" datetime="--><?php //echo date('d-m-Y',$this->arrContent[\My\General::CATEGORY_WORLD][0]['created_date']); ?><!--">-->
<!--                                                    --><?php //echo date('d-m-Y',$this->arrContent[\My\General::CATEGORY_WORLD][0]['created_date']); ?>
<!--                                                </time>-->
<!--                                            </span>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="td-big-grid-scroll">
                                <div class="td_module_mx6 td-animation-stack td-big-grid-post-1 td-big-grid-post td-small-thumb">
                                    <div class="td-module-thumb">
                                        <a rel="nofollow" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_SHOWBIZ][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_SHOWBIZ][0]['cont_id']]) ?>"
                                            rel="bookmark"
                                            title="<?php echo $this->arrContent[\My\General::CATEGORY_SHOWBIZ][0]['cont_title'] ?>">
                                            <img width="265" height="198"
                                               class="entry-thumb td-animation-stack-type0-2"
                                               src="<?php echo $this->arrContent[\My\General::CATEGORY_SHOWBIZ][0]['cont_resize_image'] ?>"
                                               alt="<?php echo $this->arrContent[\My\General::CATEGORY_SHOWBIZ][0]['cont_title'] ?>"
                                               title="<?php echo $this->arrContent[\My\General::CATEGORY_SHOWBIZ][0]['cont_title'] ?>">
                                        </a>
                                    </div>
                                    <div class="td-meta-info-container">
                                        <div class="td-meta-align">
                                            <div class="td-big-grid-meta">
                                                <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategory[\My\General::CATEGORY_SHOWBIZ]['cate_slug'], 'cateId' => $this->arrCategory[\My\General::CATEGORY_SHOWBIZ]['cate_id']]) ?>"
                                                   class="td-post-category">
                                                    <?php echo $this->arrCategory[\My\General::CATEGORY_SHOWBIZ]['cate_name'] ?>
                                                </a>
                                                <h3 class="entry-title td-module-title">
                                                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_SHOWBIZ][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_SHOWBIZ][0]['cont_id']]) ?>"
                                                        rel="bookmark"
                                                        title="<?php echo $this->arrContent[\My\General::CATEGORY_SHOWBIZ][0]['cont_title'] ?>">
                                                        <?php echo $this->arrContent[\My\General::CATEGORY_SHOWBIZ][0]['cont_title'] ?>
                                                    </a>
                                                </h3>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_mx6 td-animation-stack td-big-grid-post-2 td-big-grid-post td-small-thumb">
                                    <div class="td-module-thumb">
                                        <a rel="nofollow" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_TECH][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_TECH][0]['cont_id']]) ?>"
                                            rel="bookmark"
                                            title="<?php echo $this->arrContent[\My\General::CATEGORY_TECH][0]['cont_title'] ?>">
                                            <img width="265" height="198" class="entry-thumb td-animation-stack-type0-2"
                                                src="<?php echo $this->arrContent[\My\General::CATEGORY_TECH][0]['cont_resize_image'] ?>"
                                                alt="<?php echo $this->arrContent[\My\General::CATEGORY_TECH][0]['cont_title'] ?>"
                                                title="<?php echo $this->arrContent[\My\General::CATEGORY_TECH][0]['cont_title'] ?>">
                                        </a>
                                    </div>
                                    <div class="td-meta-info-container">
                                        <div class="td-meta-align">
                                            <div class="td-big-grid-meta">
                                                <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategory[\My\General::CATEGORY_TECH]['cate_slug'], 'cateId' => $this->arrCategory[\My\General::CATEGORY_TECH]['cate_id']]) ?>"
                                                   class="td-post-category">
                                                    <?php echo $this->arrCategory[\My\General::CATEGORY_TECH]['cate_name'] ?>
                                                </a>
                                                <h3 class="entry-title td-module-title">
                                                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_TECH][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_TECH][0]['cont_id']]) ?>"
                                                        rel="bookmark"
                                                        title="<?php echo $this->arrContent[\My\General::CATEGORY_TECH][0]['cont_title'] ?>">
                                                        <?php echo $this->arrContent[\My\General::CATEGORY_TECH][0]['cont_title'] ?>
                                                    </a>
                                                </h3>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_mx6 td-animation-stack td-big-grid-post-3 td-big-grid-post td-small-thumb">
                                    <div class="td-module-thumb">
                                        <a rel="nofollow" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_HEALTH][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_HEALTH][0]['cont_id']]) ?>"
                                            rel="bookmark"
                                            title="<?php echo $this->arrContent[\My\General::CATEGORY_HEALTH][0]['cont_title'] ?>">
                                            <img width="265" height="198" class="entry-thumb td-animation-stack-type0-2"
                                                src="<?php echo $this->arrContent[\My\General::CATEGORY_HEALTH][0]['cont_resize_image'] ?>"
                                                alt="<?php echo $this->arrContent[\My\General::CATEGORY_HEALTH][0]['cont_title'] ?>"
                                                 title="<?php echo $this->arrContent[\My\General::CATEGORY_HEALTH][0]['cont_title'] ?>">
                                        </a>
                                    </div>
                                    <div class="td-meta-info-container">
                                        <div class="td-meta-align">
                                            <div class="td-big-grid-meta">
                                                <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategory[\My\General::CATEGORY_HEALTH]['cate_slug'], 'cateId' => $this->arrCategory[\My\General::CATEGORY_HEALTH]['cate_id']]) ?>"
                                                   class="td-post-category">
                                                    <?php echo $this->arrCategory[\My\General::CATEGORY_HEALTH]['cate_name'] ?>
                                                </a>
                                                <h3 class="entry-title td-module-title">
                                                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_HEALTH][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_HEALTH][0]['cont_id']]) ?>"
                                                        rel="bookmark"
                                                        title="<?php echo $this->arrContent[\My\General::CATEGORY_HEALTH][0]['cont_title'] ?>"><?php echo $this->arrContent[\My\General::CATEGORY_HEALTH][0]['cont_title'] ?>
                                                    </a>
                                                </h3>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_mx6 td-animation-stack td-big-grid-post-4 td-big-grid-post td-small-thumb">
                                    <div class="td-module-thumb">
                                        <a rel="nofollow" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_NATURALLY_SAVVY][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_NATURALLY_SAVVY][0]['cont_id']]) ?>"
                                            rel="bookmark" title="<?php echo $this->arrContent[\My\General::CATEGORY_NATURALLY_SAVVY][0]['cont_title'] ?>">
                                            <img width="265" height="198"
                                                  class="entry-thumb td-animation-stack-type0-2"
                                                  src="<?php echo $this->arrContent[\My\General::CATEGORY_NATURALLY_SAVVY][0]['cont_resize_image'] ?>"
                                                  alt="<?php echo $this->arrContent[\My\General::CATEGORY_NATURALLY_SAVVY][0]['cont_title'] ?>"
                                                  title="<?php echo $this->arrContent[\My\General::CATEGORY_NATURALLY_SAVVY][0]['cont_title'] ?>">
                                        </a>
                                    </div>
                                    <div class="td-meta-info-container">
                                        <div class="td-meta-align">
                                            <div class="td-big-grid-meta">
                                                <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategory[\My\General::CATEGORY_NATURALLY_SAVVY]['cate_slug'], 'cateId' => $this->arrCategory[\My\General::CATEGORY_NATURALLY_SAVVY]['cate_id']]) ?>"
                                                   class="td-post-category">
                                                    <?php echo $this->arrCategory[\My\General::CATEGORY_NATURALLY_SAVVY]['cate_name'] ?>
                                                </a>
                                                <h3 class="entry-title td-module-title">
                                                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_NATURALLY_SAVVY][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_NATURALLY_SAVVY][0]['cont_id']]) ?>"
                                                        rel="bookmark" title="<?php echo $this->arrContent[\My\General::CATEGORY_NATURALLY_SAVVY][0]['cont_title'] ?>">
                                                        <?php echo $this->arrContent[\My\General::CATEGORY_NATURALLY_SAVVY][0]['cont_title'] ?>
                                                    </a>
                                                </h3>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
