<?php
$arr_category_info = unserialize(ARR_CATEGORY_INFO);
$arr_content = $this->arrContent;
?>
<div id="adindexcenter" class="adbox" style="margin-bottom:20px;">
    <div id="adindexcenter" class="adbox" style="margin-bottom:20px;">
        <img src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/640x60.png'; ?>">
<!--        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>-->
<!--        <!-- tuoitre.mobi -->-->
<!--        <ins class="adsbygoogle"-->
<!--             style="display:inline-block;"-->
<!--             data-ad-client="ca-pub-9166980393030854"-->
<!--             data-ad-slot="5007199245"></ins>-->
<!--        <script>-->
<!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
<!--        </script>-->
    </div>
</div>
<a class="hd" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $arr_category_info[\My\General::CATEGORY_CONG_NGHE]['cate_slug'], 'cateId' => $arr_category_info[\My\General::CATEGORY_KHOA_HOC]['cate_id']]) ?>">
    <?php echo $arr_category_info[\My\General::CATEGORY_CONG_NGHE]['cate_name'] ?>
</a>
<div class="listview clearfix">
    <ul>
        <?php foreach ($arr_content[\My\General::CATEGORY_CONG_NGHE] as $content): ?>
            <li class="listitem clearfix">
                <a class="title" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>">
                    <?php echo $content['cont_title'] ?>
                </a>
                <a class="thumb" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>">
                    <img src="<?php echo $content['cont_main_image'] ?>"
                         alt="<?php echo $content['cont_title'] ?>"/>
                </a>
                <div class="desc">
                    <?php echo $content['cont_description'] ?>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<a class="viewmore" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $arr_category_info[\My\General::CATEGORY_CONG_NGHE]['cate_slug'], 'cateId' => $arr_category_info[\My\General::CATEGORY_CONG_NGHE]['cate_id']]) ?>">
    Xem thêm
</a>

