<?php
$arr_content = $this->arrContentList;
?>

<div class="content">
    <div id="adindexcenter" class="adbox" style="margin-bottom:20px;">
        <img src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/640x60.png'; ?>">
<!--        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>-->
<!--        <ins class="adsbygoogle"-->
<!--             style="display:inline-block;"-->
<!--             data-ad-client="ca-pub-9166980393030854"-->
<!--             data-ad-slot="5007199245"></ins>-->
<!--        <script>-->
<!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
<!--        </script>-->
    </div>
    <div class="listview clearfix">
        <ul>
            <?php foreach($arr_content as $content):
                    ?>
                    <li class="listitem clearfix">
                        <a class="title"
                           href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>">
                            <?php echo $content['cont_title'] ?>
                        </a>
                        <a class="thumb"
                           href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>">
                            <img src="<?php echo $content['cont_main_image'] ?>"
                                 alt="<?php echo $content['cont_title'] ?>">
                        </a>
                        <div class="desc"><?php echo $content['cont_description'] ?></div>

                        <?php if($content['list_keyword']){ ?>
                        <div class="tag">
                            <ul class="td-tags-keyword clearfix">
                                <li><span>Xem thêm: </span></li>
                                <?php foreach ($content['list_keyword'] as $keyword) { ?>
                                    <li>
                                        <a href="<?php echo $this->serverUrl() . $this->Url('keyword', ['keyId' => $keyword['key_id'],'keySlug' => $keyword['key_slug']]) ?>"><?php echo $keyword['key_name'] ?></a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                        <?php } ?>

                    </li>
                <?php endforeach;
            ?>
        </ul>
    </div>
    <div id="adsinfeed" class="adbox" style="margin-bottom:20px">
<!--        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>-->
<!--        <ins class="adsbygoogle"-->
<!--             style="display:inline-block;"-->
<!--             data-ad-client="ca-pub-9166980393030854"-->
<!--             data-ad-slot="5007199245"></ins>-->
<!--        <script>-->
<!--            (adsbygoogle = window.adsbygoogle || []).push({});-->
<!--        </script>-->
    </div>
</div>