<?php
$arr_category = unserialize(ARR_CATEGORY);
$keyDetail = $this->arrKeyDetail;

$content_crawler = $keyDetail['content_crawler']!= '1' ? json_decode($keyDetail['content_crawler'], true) : '1';
?>
<div class=td-crumb-container>
    <div class=entry-crumbs>
        <span>
            <a title="" class="entry-crumb" itemprop="url" href="<?php echo $this->serverUrl() . $this->Url('home') ?>">
                <span itemprop="title"><i class="fa fa-home"></i> Home</span>
            </a>
        </span>
        <i class="td-icon-right td-bread-sep td-bred-no-url-last"></i>
        <span class="td-bred-no-url-last">
            <meta itemprop="title" content="Từ khóa">
            <meta itemprop="url" content="<?php echo $this->serverUrl() . $this->Url('keyword', ['keyId' => $this->params['keyId'],'keySlug' => $this->params['keySlug']]) ?>">Từ khóa
        </span>
    </div>
</div>

<div class="td-ss-main-content">
    <div class="td-page-header">
        <h1 class="entry-title td-page-title td-search-query">
            <?php echo $keyDetail['key_name'] ?>
        </h1>
<!--        <p>Tìm thấy <b>--><?php //echo $this->intTotal; ?><!--</b> bài viết liên quan</p>-->
    </div>
    <?php if (!empty($this->arrContentList)){ $i = 1;
        foreach ($this->arrContentList as $arr_content):
            if($i == 1 || $i == 5) {
                ?>
                <div class="td-a-rec td-a-rec-id-header" style="margin-bottom: 30px">
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- tintuc360.me -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-9166980393030854"
                         data-ad-slot="5007199245"
                         data-ad-format="auto"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
            <?php } ?>

            <?php if($i == 2 && $content_crawler != '1'){ ?>
            <div class="td-post-content" style="margin-top: 0px">
                <?php foreach ($content_crawler as $item){ ?>
                    <p style="margin-bottom: 10px"><?php echo $item['description'] ?></p>
                <?php } ?>
            </div>
            <?php } ?>

            <div class="td_module_10 td_module_wrap td-animation-stack">
                <div class=td-module-thumb>
                    <a rel="nofollow" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>" rel=bookmark title="<?php echo $arr_content['cont_title'] ?>">
                        <img width="218" height="150" class=entry-thumb src="<?php echo $arr_content['cont_resize_image'] ?>" alt="<?php echo $arr_content['cont_title'] ?>"/>
                    </a>
                </div>
                <div class=item-details>
                    <h3 class="entry-title td-module-title">
                        <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>" rel=bookmark
                           title="<?php echo $arr_content['cont_title'] ?>">
                            <?php echo (strlen($arr_content['cont_title']) < 150) ? $arr_content['cont_title'] : mb_substr($arr_content['cont_title'], 0, 150, 'UTF-8') . '...'; ?>
                        </a>
                    </h3>
                    <div class=td-module-meta-info>
                        <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $arr_category[$arr_content['cate_id']]['cate_slug'], 'cateId' => $arr_category[$arr_content['cate_id']]['cate_id']]) ?>" class="td-post-category">
                            <?php echo $arr_category[$arr_content['cate_id']]['cate_name'] ?>
                        </a>
                        <span class=td-post-date>
                            <time class="entry-date updated td-module-date"
                                  datetime="<?php echo date("d-m-Y", $arr_content['created_date']); ?>"><?php echo date("d-m-Y", $arr_content['created_date']); ?></time>
                        </span>
                    </div>
                    <div class="td-excerpt">
                        <?php echo (strlen($arr_content['cont_description']) < 300) ? $arr_content['cont_description'] : mb_substr($arr_content['cont_description'], 0, 300, 'UTF-8') . '... '; ?>
                    </div>
                    <div class="td-post-source-tags">
                        <ul class="td-tags td-post-small-box clearfix">
                            <li><span>KEYWORD</span></li>
                            <?php foreach ($arr_content['list_keyword'] as $keyword){ ?>
                                <li><a href="<?php echo $this->serverUrl() . $this->Url('keyword', ['keyId' => $keyword['key_id'], 'keySlug' => $keyword['key_slug']]) ?>"><?php echo $keyword['key_name'] ?></a></li>
                            <?php } ?>
                        </ul>
                    </div>

                </div>
            </div>
            <?php
        $i ++;
        endforeach;
    } else {
        ?>
        <div class="td-a-rec td-a-rec-id-header" style="margin-bottom: 30px">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- tintuc360.me -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-9166980393030854"
                 data-ad-slot="5007199245"
                 data-ad-format="auto"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>

        <?php if($content_crawler != '1'){ ?>
            <div class="td-post-content" style="margin-top: 0px">
                <?php foreach ($content_crawler as $item){ ?>
                    <p style="margin-bottom: 10px"><?php echo $item['description'] ?></p>
                <?php } ?>
            </div>
        <?php } ?>
    <?php } ?>
</div>
<!--<div class="page-nav td-pb-padding-side">-->
<!--    --><?php //echo $this->paging; ?>
<!--</div>-->
