<div class="content">
    <h1>Danh sách từ khoá</h1>
    <div class="taxdesc">
    </div>
    <div class="breadcrumbs info-detail" xmlns:v="http://rdf.data-vocabulary.org/#">
        <span class="first breadcrumb">
            <a href="<?php echo BASE_URL; ?>">🏠</a>
        </span>
        <span typeof="v:Breadcrumb" class="breadcrumb">
            <a rel="v:url" property="v:title"
               href="<?php echo $this->serverUrl() . $this->Url('list-keyword') ?>">
                Danh sách từ khoá
            </a>
        </span>
    </div>

    <div id="adindexcenter" class="adbox" style="margin-bottom:20px;">
        <!-- TT360 Responsive Article -->
        <ins class="adsbygoogle"
             style="display:inline-block;width: 640px;height: 60px"
             data-ad-client="ca-pub-9166980393030854"
             data-ad-slot="5007199245"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
    
    <div class="listitems">
        <ul>
            <?php if (!empty($this->arrKeywordList)):
                foreach ($this->arrKeywordList as $arr_key):
                    ?>
                    <li>
                        <a href="<?php echo $this->serverUrl() . $this->Url('keyword', array('keySlug' => $arr_key['key_slug'], 'keyId' => $arr_key['key_id'])) ?>">
                            <?php echo $arr_key['key_name']; ?>
                        </a>
                    </li>
                <?php endforeach;
            endif;
            ?>
        </ul>
    </div>

    <div class="pagination-container">
        <ul class="pagination">
            <?php echo $this->paging; ?>
        </ul>
    </div>
</div>