<?php
$paramsRouter = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParams();
$routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$controller = $paramsRouter['__CONTROLLER__'];
$action = $paramsRouter['action'];
?>

<div class="slider">
    <ul>
        <li>
            <a href="huong-dan-chinh-sua-hinh-anh-nghe-thuat-tren-pitu-130342.html">
                <img class="thumb"
                     src="../img.quantrimang.com/photos/image/2017/02/13/Pitu-chinh-anh-logo650-size-640x335-znd.jpg"
                     alt="Hướng dẫn chụp ảnh cổ trang bằng Pitu tr&#234;n điện thoại"/>
                <span>Hướng dẫn chụp ảnh cổ trang bằng Pitu tr&#234;n điện thoại</span>
            </a>
        </li>
    </ul>
</div>


<div id="adindexcenter" class="adbox" style="margin-bottom:20px;">

    <!-- QTM Responsive Article -->
    <div style="min-height:15px">
        <!-- Quantrimang Links - Dapung1 -->
    </div>
</div>
<div class="ListNews">
    <a class="hd" href="cong-nghe.html">C&#244;ng nghệ</a>
    <div class="post-news">
        <a class="title" href="cach-gan-co-to-quoc-vao-anh-profile-facebook-130528.html">
            Hướng dẫn gắn cờ Tổ quốc v&#224;o ảnh profile Facebook
        </a>
        <a class="img-news" href="cach-gan-co-to-quoc-vao-anh-profile-facebook-130528.html">
            <img class="thumb"
                 src="../img.quantrimang.com/photos/image/2017/02/24/Facebook-profile-logo-size-640x250-znd.jpg">
        </a>
        <div class="desc-news">Facebook đã cho phép người dùng có thể gắn cờ Tổ quốc vào hình ảnh đại diện của mình trên
            Facebook phiên bản máy tính lẫn ứng dụng trên Android, iOS. Chúng ta có thể tìm kiếm lá cờ quốc gia của mình
            và sau đó ghép vào hình ảnh profile.
        </div>
    </div>
    <div class="listview clearfix">
        <ul>
            <li class="listitem clearfix">
                <a class="title" href="cach-kiem-tra-iphone-lock-thuoc-nha-mang-nao-130523.html">
                    C&#225;ch kiểm tra iPhone Lock thuộc nh&#224; mạng n&#224;o
                </a>
                <a class="thumb" href="cach-kiem-tra-iphone-lock-thuoc-nha-mang-nao-130523.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/23/iPhone-Lock-nha-mang-logo200.jpg"
                         alt="C&#225;ch kiểm tra iPhone Lock thuộc nh&#224; mạng n&#224;o"/>
                </a>
                <div class="desc">Hiện nay, iPhone Lock chủ yếu đến từ thị trường Mỹ và Nhật Bản. Tuy nhiên, nếu bạn
                    không chắc chắn về phiên bản iPhone Lock của mình thì có thể thực hiện kiểm tra ngay trên thiết bị.
                </div>
            </li>
        </ul>
    </div>
    <div class="listview clearfix">
        <ul>
            <li class="listitem clearfix">
                <a class="title" href="nhung-ung-dung-can-thiet-cho-nguoi-moi-dung-iphone-130548.html">
                    Những ứng dụng cần thiết cho người mới d&#249;ng iPhone
                </a>
                <a class="thumb" href="nhung-ung-dung-can-thiet-cho-nguoi-moi-dung-iphone-130548.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/25/ung-dung-iphone-200.jpg"
                         alt="Những ứng dụng cần thiết cho người mới d&#249;ng iPhone"/>
                </a>
                <div class="desc">Bạn mới mua iPhone và không biết phải sử dụng ứng dụng gì? Bài viết dưới đây sẽ tổng
                    hợp một số ứng dụng cần thiết cho người mới dùng iPhone như Facebook, Zalo, Viber, Twitter, Twitch,
                    Talktv, Dropbox. Office...
                </div>
            </li>
            <li class="listitem clearfix">
                <a class="title" href="6-ham-huu-ich-trong-google-sheets-co-the-ban-chua-biet-130552.html">
                    6 h&#224;m hữu &#237;ch trong Google Sheets c&#243; thể bạn chưa biết
                </a>
                <a class="thumb" href="6-ham-huu-ich-trong-google-sheets-co-the-ban-chua-biet-130552.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/22/GoogleSpreadsheet-200.jpg"
                         alt="6 h&#224;m hữu &#237;ch trong Google Sheets c&#243; thể bạn chưa biết"/>
                </a>
                <div class="desc">Trong bài viết này, tôi sẽ chỉ ra 6 hàm hữu ích dành cho bảng tính Google Sheets mà
                    bạn nên biết như hàm Vlookup, CountIF, SumIF, JOIN,INDEX,...Ngoài ra, các bạn có thể tham khảo thêm
                    các hàm và mẹo khác theo đường link có trong bài.
                </div>
            </li>
            <li class="listitem clearfix">
                <a class="title" href="top-ung-dung-khoa-hoc-cho-tre-tren-android-130544.html">
                    Top ứng dụng khoa học cho trẻ tr&#234;n Android
                </a>
                <a class="thumb" href="top-ung-dung-khoa-hoc-cho-tre-tren-android-130544.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/25/ung-dung-khoa-hoc-cho-tre-200.jpg"
                         alt="Top ứng dụng khoa học cho trẻ tr&#234;n Android"/>
                </a>
                <div class="desc">Muốn trẻ làm quen với khoa học một cách nhanh chóng và dễ dàng. Hãy tham khảo 3 ứng
                    dụng khoa học cho trẻ trên Android là Kid Science Amazing Experiments, Alchemy - Genetics, Animal
                    Kingdom Science for Kids.
                </div>
            </li>
        </ul>
    </div>
    <a class="viewmore" href="cong-nghe.html">Xem thêm</a>
    <a class="hd" href="khoa-hoc.html">Khoa học</a>
    <div class="post-news">
        <a class="title"
           href="bom-hydro-vu-khi-hat-nhan-co-suc-cong-pha-manh-gap-1000-lan-so-voi-bom-nguyen-tu-130553.html">
            Bom hydro, vũ kh&#237; hạt nh&#226;n c&#243; sức c&#244;ng ph&#225; mạnh gấp 1000 lần so với bom nguy&#234;n
            tử
        </a>
        <a class="img-news"
           href="bom-hydro-vu-khi-hat-nhan-co-suc-cong-pha-manh-gap-1000-lan-so-voi-bom-nguyen-tu-130553.html">
            <img class="thumb"
                 src="../img.quantrimang.com/photos/image/2017/02/25/bom-nguyen-tu-650-size-640x250-znd.jpg">
        </a>
        <div class="desc-news">Hãy thử so sánh để xem bom nguyên tử và bom hydro khác nhau như thế nào? Sức công phá của
            mỗi loại bom khủng khiếp ra sao nhé.
        </div>
    </div>
    <div class="listview clearfix">
        <ul>
            <li class="listitem clearfix">
                <a class="title" href="bi-quyet-song-khoe-va-truong-tho-loi-khuyen-tu-cac-chuyen-gia-130551.html">
                    B&#237; quyết sống khỏe v&#224; trường thọ lời khuy&#234;n từ c&#225;c chuy&#234;n gia
                </a>
                <a class="thumb" href="bi-quyet-song-khoe-va-truong-tho-loi-khuyen-tu-cac-chuyen-gia-130551.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/25/song-khoe-200.jpg"
                         alt="B&#237; quyết sống khỏe v&#224; trường thọ lời khuy&#234;n từ c&#225;c chuy&#234;n gia"/>
                </a>
                <div class="desc">Bạn có muốn sống tới 100 tuổi không? Hãy đọc ba lần “bí quyết” khỏe mạnh hạnh phúc và
                    trường thọ sau đây.
                </div>
            </li>
            <li class="listitem clearfix">
                <a class="title" href="cach-loai-vat-nhin-the-gioi-vuot-xa-con-nguoi-nhu-the-nao-130547.html">
                    C&#225;ch lo&#224;i vật nh&#236;n thế giới vượt xa con người như thế n&#224;o?
                </a>
                <a class="thumb" href="cach-loai-vat-nhin-the-gioi-vuot-xa-con-nguoi-nhu-the-nao-130547.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/25/loai-vat-200.jpg"
                         alt="C&#225;ch lo&#224;i vật nh&#236;n thế giới vượt xa con người như thế n&#224;o?"/>
                </a>
                <div class="desc">Loài vật nhìn thế giới như thế nào, có gì khác với con người? Bạn sẽ bất ngờ khi biết
                    rằng chúng nhìn thế giới bằng những cách rất khác chúng ta, con người dù tiến hóa cao cấp cũng khó
                    có được những khả năng này.
                </div>
            </li>
            <li class="listitem clearfix">
                <a class="title"
                   href="microsoft-research-dang-tao-ra-mot-ai-co-kha-nang-tu-viet-code-trong-vai-giay-130542.html">
                    Microsoft Research đang tạo ra m&#244;̣t AI có khả năng tự vi&#234;́t code trong v&#224;i gi&#226;y
                </a>
                <a class="thumb"
                   href="microsoft-research-dang-tao-ra-mot-ai-co-kha-nang-tu-viet-code-trong-vai-giay-130542.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/24/phat-minh-moi-200.jpg"
                         alt="Microsoft Research đang tạo ra m&#244;̣t AI có khả năng tự vi&#234;́t code trong v&#224;i gi&#226;y"/>
                </a>
                <div class="desc">Microsoft Research đang hợp tác với các nhà nghiên cứu tại trường Đại học
                    Cambridge để phát triển một hệ thống trí tuệ thông minh AI, có khả năng tự viết code trong
                    vài giây.
                </div>
            </li>
            <li class="listitem clearfix">
                <a class="title"
                   href="chat-doc-vx-loai-chat-doc-khung-khiep-nhat-the-gioi-dang-so-nhu-the-nao-130541.html">
                    Chất độc VX, loại chất độc thần kinh khủng khiếp nhất thế giới đ&#225;ng sợ như thế n&#224;o?
                </a>
                <a class="thumb"
                   href="chat-doc-vx-loai-chat-doc-khung-khiep-nhat-the-gioi-dang-so-nhu-the-nao-130541.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/24/chat-doc-200.jpg"
                         alt="Chất độc VX, loại chất độc thần kinh khủng khiếp nhất thế giới đ&#225;ng sợ như thế n&#224;o?"/>
                </a>
                <div class="desc">VX là một chất độc thần kinh được đánh giá là mạnh nhất mà con người từng tạo ra. Nó
                    mạnh hơn 100 lần so với Srarin - chất độc gây chết người chỉ trong vài phút với liều lượng cực nhỏ.
                    Liên Hợp Quốc đã xếp loại chất độc này vào danh sách "Vũ khí hủy diệt hàng loạt".
                </div>
            </li>
            <li class="listitem clearfix">
                <a class="title"
                   href="nhung-thua-can-o-tuoi-20-co-60-80-nguy-co-mac-benh-ung-thu-da-day-sau-nay-130504.html">
                    Những thừa c&#226;n ở tuổi 20 c&#243; 60-80% nguy cơ mắc bệnh ung thư dạ d&#224;y sau n&#224;y
                </a>
                <a class="thumb"
                   href="nhung-thua-can-o-tuoi-20-co-60-80-nguy-co-mac-benh-ung-thu-da-day-sau-nay-130504.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/24/beo-phi-co-the-bi-benh-da-day-200.jpg"
                         alt="Những thừa c&#226;n ở tuổi 20 c&#243; 60-80% nguy cơ mắc bệnh ung thư dạ d&#224;y sau n&#224;y"/>
                </a>
                <div class="desc">Bài viết như lời cảnh tỉnh cho những bạn trẻ nào đang ở độ tuổi 20 đang mắc tình trạng
                    thừa cân, béo phì.
                </div>
            </li>
        </ul>
    </div>
    <a class="viewmore" href="khoa-hoc.html">Xem thêm</a>
    <a class="hd" href="cuoc-song.html">Cuộc sống</a>
    <div class="post-news">
        <a class="title" href="13-website-kiem-tien-truc-tuyen-tot-nhat-hien-nay-127057.html">
            13 website kiếm tiền trực tuyến tốt nhất hiện nay
        </a>
        <a class="img-news" href="13-website-kiem-tien-truc-tuyen-tot-nhat-hien-nay-127057.html">
            <img class="thumb"
                 src="../img.quantrimang.com/photos/image/2016/11/05/website-tim-kiem-tot-nhat-hien-nay-650-size-640x250-znd.jpg">
        </a>
        <div class="desc-news">Hãy cùng tham khảo 13 website tốt nhất dưới đây giúp bạn có thể sử dụng để kiếm nhiều
            tiền hơn trong thời đại công nghệ hiện nay nhé!
        </div>
    </div>
    <div class="listview clearfix">
        <ul>
            <li class="listitem clearfix">
                <a class="title"
                   href="16-dieu-nen-lam-vao-sang-thu-hai-dau-tuan-de-co-the-lam-viec-hieu-qua-hon-130546.html">
                    16 điều n&#234;n l&#224;m v&#224;o s&#225;ng thứ Hai đầu tuần để c&#243; thể l&#224;m việc hiệu quả
                    hơn
                </a>
                <a class="thumb"
                   href="16-dieu-nen-lam-vao-sang-thu-hai-dau-tuan-de-co-the-lam-viec-hieu-qua-hon-130546.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/25/sang-thu-hai-200.jpg"
                         alt="16 điều n&#234;n l&#224;m v&#224;o s&#225;ng thứ Hai đầu tuần để c&#243; thể l&#224;m việc hiệu quả hơn"/>
                </a>
                <div class="desc">Hãy cùng tham khảo 16 điều nên làm vào sáng thứ Hai đầu tuần dưới đây để có thể làm
                    việc hiệu quả hơn nhé!
                </div>
            </li>
            <li class="listitem clearfix">
                <a class="title" href="rang-trang-xinh-ma-khong-can-dung-den-hoa-chat-130532.html">
                    Răng trắng xinh m&#224; kh&#244;ng cần d&#249;ng đến h&#243;a chất
                </a>
                <a class="thumb" href="rang-trang-xinh-ma-khong-can-dung-den-hoa-chat-130532.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/24/trang-rang-200.jpg"
                         alt="Răng trắng xinh m&#224; kh&#244;ng cần d&#249;ng đến h&#243;a chất"/>
                </a>
                <div class="desc">"Cái răng cái tóc là góc con người" nhưng đại đa số người dân Việt Nam lại mắc các
                    bệnh về răng miệng, ảnh hưởng lớn đến thẩm mỹ và sức khỏe. Vậy làm sao để răng được trắng sáng mà
                    lại an toàn cho sức khỏe.
                </div>
            </li>
            <li class="listitem clearfix">
                <a class="title" href="5-bi-kip-can-thiet-de-lam-viec-tai-nha-mot-cach-hieu-qua-130534.html">
                    5 b&#237; k&#237;p cần thiết để l&#224;m việc tại nh&#224; một c&#225;ch hiệu quả
                </a>
                <a class="thumb" href="5-bi-kip-can-thiet-de-lam-viec-tai-nha-mot-cach-hieu-qua-130534.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/24/lam-viec-200.jpg"
                         alt="5 b&#237; k&#237;p cần thiết để l&#224;m việc tại nh&#224; một c&#225;ch hiệu quả"/>
                </a>
                <div class="desc">Làm việc tại nhà không chỉ tiện lợi cho việc di chuyển, không phải đi xa, không phải
                    chịu nắng mưa hay khói bụi trên đường đến công ty mà còn giúp bạn linh động về thời gian biểu hàng
                    ngày. Hãy chú ý đến 5 điều này để mỗi ngày làm việc ở nhà trở nên hiệu quả hơn nhé!
                </div>
            </li>
            <li class="listitem clearfix">
                <a class="title" href="dung-bao-gio-lam-6-dieu-nay-voi-nguoi-dan-ong-cua-ban-130531.html">
                    Đừng bao giờ l&#224;m 6 điều n&#224;y với người đ&#224;n &#244;ng của bạn
                </a>
                <a class="thumb" href="dung-bao-gio-lam-6-dieu-nay-voi-nguoi-dan-ong-cua-ban-130531.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/24/tinh-yeu-200.jpg"
                         alt="Đừng bao giờ l&#224;m 6 điều n&#224;y với người đ&#224;n &#244;ng của bạn"/>
                </a>
                <div class="desc">Nếu là người phụ nữ thông minh, đừng bao giờ làm 6 điều này với người đàn ông của bạn
                    nhé!
                </div>
            </li>
            <li class="listitem clearfix">
                <a class="title" href="cach-pha-nuoc-ngam-chan-cho-ngay-dai-thu-gian-130527.html">
                    Pha nước ng&#226;m ch&#226;n để khử m&#249;i h&#244;i v&#224; chống mỏi ch&#226;n hiệu quả
                </a>
                <a class="thumb" href="cach-pha-nuoc-ngam-chan-cho-ngay-dai-thu-gian-130527.html">
                    <img src="../img.quantrimang.com/photos/image/2017/02/24/ngam-chan-200.jpg"
                         alt="Pha nước ng&#226;m ch&#226;n để khử m&#249;i h&#244;i v&#224; chống mỏi ch&#226;n hiệu quả"/>
                </a>
                <div class="desc">Bàn chân được mệnh danh là "trái tim thứ 2" của cơ thể vì chứa nhiều huyệt đạo quan
                    trọng. Đó là lý do tại sao khi ngâm chân xong bạn thường cảm thấy dễ chịu, thoải mái.
                </div>
            </li>
        </ul>
    </div>
    <a class="viewmore" href="cuoc-song.html">Xem thêm</a>
</div>
    