<!-- FOOTER -->
<div id="footer" class="clearfix">
    <div class="info">
        <div class="bottomlinks">
            <a href="#" rel="nofollow">Liên hệ</a> |
            <a href="#" rel="nofollow" target="_blank">Facebook</a> |
            <a href="#" rel="nofollow" target="_blank">Youtube</a> |
            <a href="#" rel="publisher" target="_blank">Google+</a> |
            <a href="#" target="_blank">Rss</a>
        </div>
    </div>
    <div class="copyright">
        Tuoitre.mobi.<br>
    </div>
</div>

<!-- END FOOTER -->