<!-- FOOTER -->
<div class=td-footer-wrapper>

    <div class=td-footer-bottom-full>
        <div class=td-container>
            <div class=td-pb-row>
                <div class=td-pb-span3>
                    <aside class=footer-logo-wrap>
                        <a href="<?php echo $this->serverUrl() . $this->Url('home') ?>">
                            <img class=td-retina-data src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/logo-hello-black.png'; ?>"
                                data-retina="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/logo-hello-black.png'; ?>" alt="Hellonews" title="Hellonews"/>
                        </a>
                    </aside>
                </div>
                <div class=td-pb-span5>
                    <aside class=footer-text-wrap>
                        <div class=block-title><span>ABOUT US</span></div>
                        Cổng tin tức tổng hợp, cung cấp thông tin thiết thực, hữu ích cho cuộc sống của bạn.
                        <div class=footer-email-wrap>Contact us: <a href="">hellonews@gmail.com</a>
                        </div>
                    </aside>
                </div>
                <div class=td-pb-span4>
                    <aside class="footer-social-wrap td-social-style-2">
                        <div class=block-title><span>FOLLOW US</span></div>
                            <span class=td-social-icon-wrap>
                                <a target=_blank href="https://www.facebook.com/tintuc360.me/" title=Facebook>
                                    <i class="td-icon-font td-icon-facebook"></i>
                                </a>
                            </span>
                            <span class=td-social-icon-wrap>
                                <a target=_blank href="javascript:;" title=Twitter>
                                    <i class="td-icon-font td-icon-twitter"></i>
                                </a>
                            </span>
                            <span class=td-social-icon-wrap>
                                <a target=_blank href="javascript:;" title=Vimeo>
                                    <i class="td-icon-font td-icon-vimeo"></i>
                                </a>
                            </span>
                            <span class=td-social-icon-wrap>
                                <a target=_blank href="javascript:;" title=VKontakte>
                                    <i class="td-icon-font td-icon-vk"></i>
                                </a>
                            </span>
                            <span class=td-social-icon-wrap>
                                <a target=_blank href="javascript:;" title=Youtube>
                                    <i class="td-icon-font td-icon-youtube"></i>
                                </a>
                            </span>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- END FOOTER -->

<!-- LINE FOOTER -->
<div class=td-sub-footer-container>
    <div class=td-container>
        <div class=td-pb-row>
            <div class="td-pb-span7 td-sub-footer-menu">
                <div class=menu-footer-menu-container>
                    <ul id=menu-footer-menu class=td-subfooter-menu>
                        <li id=menu-item-17
                            class="menu-item menu-item-type-custom menu-item-object-custom td-menu-item td-normal-menu menu-item-17">
                            <a href="javascript:;">Privacy</a></li>
                        <li id=menu-item-19
                            class="menu-item menu-item-type-custom menu-item-object-custom td-menu-item td-normal-menu menu-item-19">
                            <a href="<?php echo $this->serverUrl() . $this->Url('contact') ?>">Contact us</a></li>
                    </ul>
                </div>
            </div>
            <div class="td-pb-span5 td-sub-footer-copy">
                &copy; Copyright 2016 - <a href="<?php echo $this->serverUrl() . $this->Url('home') ?>">Tintuc306.me</a>
            </div>
        </div>
    </div>
</div>

<!-- END LINE FOOTER -->	