<!-- FOOTER -->
<div id="footer" class="clearfix">
    <div class="info">
        <div class="bottomlinks">
            <a href="contact.html" rel="nofollow">Liên hệ</a> |
            <a href="https://www.facebook.com/quantrimang.com.vn" rel="nofollow" target="_blank">Facebook</a> |
            <a href="https://www.youtube.com/c/quantrimang" rel="nofollow" target="_blank">Youtube</a> |
            <a href="https://plus.google.com/+quantrimang" rel="publisher" target="_blank">Google+</a> |
            <a href="rss" target="_blank">Rss</a>
        </div>
        <div>

            Giấy phép số 362/GP-BTTTT. Bộ Thông tin và Truyền thông cấp ngày 30/06/2016.<br>
            Cơ quan chủ quản: CÔNG TY CỔ PHẦN MẠNG TRỰC TUYẾN <a href="http://meta.vn/" rel="nofollow" target="_blank">META</a>.
        </div>
    </div>
    <div class="copyright">
        Bản quyền © 2003-2017 QuanTriMang.com. Giữ toàn quyền.<br>
        Không được sao chép hoặc sử dụng hoặc phát hành lại bất kỳ nội dung nào thuộc QuanTriMang.com khi chưa được
        phép.<br>
    </div>
</div>

<!-- END FOOTER -->