<?php
$paramsRouter = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParams();
$routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$controller = $paramsRouter['__CONTROLLER__'];
$action = $paramsRouter['action'];
?>



<!-- HEADER -->
<div id="header">
    <div class="toplinks">
        <a href='https://www.facebook.com/quantrimang.com.vn' class="icon facebook" target="_blank" rel="nofollow">Facebook</a>
        <a href='https://www.youtube.com/c/quantrimang' class="icon youtube" target="_blank" rel="nofollow">Youtube</a>
        <a href="https://plus.google.com/+quantrimang" class="icon googleplus" target="_blank" rel="nofollow">Google
            Plus</a>

    </div>
    <div class="headerleft"><a href="index.html" id="logo" title="Quantrimang.com"></a></div>
    <div id="searchBox">
        <form action="<?php echo $this->serverUrl() . $this->Url('search') ?>" id="cse-search-box">
            <div>

                <input type="text" name="q" size="55" id="q" placeholder=" Tìm kiếm"/>
                <input type="submit" name="sa" value="Tìm" id="btnHeaderFind"/>

            </div>
        </form>
    </div>
    <a class="toggle menu"></a>
    <a class="toggle search"></a>
</div>
<!-- END HEADER -->

<!-- MENU -->
<div id="mainmenu">
    <ul id="topnav" class="navigation clearfix">
        <li class="item all">
            <a href="index.html"><img src="../img.quantrimang.com/photos/image/icon/home.png" /> Trang chủ</a>
        </li>

        <li class="item  tax-cong-nghe">
            <a href='cong-nghe.html'>
                <img src="../img.quantrimang.com/photos/image/icon/technology.png" />
                C&#244;ng nghệ
            </a>
        </li>
        <li class="item  tax-khoa-hoc">
            <a href='khoa-hoc.html'>
                <img src="../img.quantrimang.com/photos/image/icon/Physics-64.png" />
                Khoa học
            </a>
        </li>
        <li class="item  tax-dien-may">
            <a href='dien-may.html'>
                <img src="../img.quantrimang.com/photos/image/icon/Fridge.png" />
                Điện m&#225;y
            </a>
        </li>
        <li class="item  tax-cuoc-song">
            <a href='cuoc-song.html'>
                <img src="../img.quantrimang.com/photos/image/icon/LifeCycle.png" />
                Cuộc sống
            </a>
        </li>
        <li class="item  tax-video">
            <a href='video.html'>
                <img src="../img.quantrimang.com/photos/image/icon/Video.png" />
                Video
            </a>
        </li>
        <li class="item  tax-ung-dung">
            <a href='ung-dung.html'>
                <img src="../img.quantrimang.com/photos/image/icon/app1.png" />
                Ứng dụng
            </a>
        </li>
        <li class="item  tax-ios">
            <a href='ios.html'>
                <img src="../img.quantrimang.com/photos/image/icon/apple.png" />
                iPhone / iPad
            </a>
        </li>
        <li class="item  tax-android">
            <a href='android.html'>
                <img src="../img.quantrimang.com/photos/image/icon/android.png" />
                Android
            </a>
        </li>
        <li class="item  tax-windows-10-os">
            <a href='windows-10-os.html'>
                <img src="../img.quantrimang.com/photos/image/icon/windows.png" />
                Windows 10
            </a>
        </li>
        <li class="item  tax-ky-nang">
            <a href='ky-nang.html'>
                <img src="../img.quantrimang.com/photos/image/icon/Training.png" />
                Kỹ năng
            </a>
        </li>
    </ul>
</div>
<!-- END MENU -->


 