<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Kiến thức công nghệ khoa học và cuộc sống - Tintuc.com</title>

    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <meta property="fb:app_id" content="265611626917890"/>


    <link rel="search" type="application/opensearchdescription+xml" title="Tìm thủ thuật - Quantrimang.com"
          href="opensearch.xml">

    <link rel=stylesheet href='<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/css/style.css'; ?>'
          type='text/css'/>

    <meta name="apple-mobile-web-app-title" content="Tintuc.com"/>
    <meta name="application-name" content="Tintuc.com"/>
    <link rel="apple-touch-icon" href="favicon.192.png"/>
    <link rel="icon" sizes="192x192" href="favicon.192.png"/>

    <!--    <script async src="../pagead2.googlesyndication.com/pagead/js/f.txt"></script>-->
    <script>
        if (screen && screen.width < 480 && /Android|iPhone|Windows Phone/i.test(window.navigator.userAgent)) {
            (adsbygoogle = window.adsbygoogle || []).push({
                google_ad_client: "ca-pub-9275417305531302",
                enable_page_level_ads: true
            });
        }
    </script>
</head>

<?php
$paramsRouter = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParams();
$routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$controller = $paramsRouter['__CONTROLLER__'];
$action = $paramsRouter['action'];
?>

<body class="showheader">
<div id="main" class="cp7">
    <?php echo \My\Minifier\HtmlMin::minify($this->render('frontend/header')); ?>

    <div class="clear"></div>

    <!-- CONTENT -->
    <div id="contentMain" class="clearfix">
        <?php echo \My\Minifier\HtmlMin::minify($this->layout()->content); ?>
        <div class="sidebar">
            <?php echo \My\Minifier\HtmlMin::minify($this->render('frontend/sidebar')); ?>
        </div>
        <div class="leftbar">
            <?php echo \My\Minifier\HtmlMin::minify($this->render('frontend/leftbar')); ?>
        </div>
    </div>

    <div class="clear"></div>

    <?php echo \My\Minifier\HtmlMin::minify($this->render('frontend/footer')); ?>
</div>
<?php echo $this->headScript(); ?>
</body>
</html>
