<?php
$paramsRouter = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParams();
$routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$controller = $paramsRouter['__CONTROLLER__'];
$action = $paramsRouter['action'];
$arr_category = unserialize(ARR_CATEGORY);
?>

<div class="navbox sidenav">
    <ul class="navigation clearfix">
        <li class="tax-cong-nghe">
            <a href="cong-nghe.html">
                <img src="../img.quantrimang.com/photos/image/icon/technology.png"/>
                C&#244;ng nghệ
            </a>
            <ul>
                <li class="tax-ung-dung  hassub">
                    <a href="ung-dung.html">
                        <img src="../img.quantrimang.com/photos/image/icon/app1.png"/>
                        Ứng dụng
                    </a>
                    <ul>
                        <li>
                            <a href="chat-nhan-tin-goi-dien.html">
                                <img src="../img.quantrimang.com/photos/image/icon/sms.png"/>
                                Chat, Nhắn tin, Gọi điện
                            </a>
                        </li>
                        <li>
                            <a href="mang-xa-hoi.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Social.png"/>
                                Mạng x&#227; hội
                            </a>
                        </li>
                        <li>
                            <a href="phan-mem-nhac.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Music-32.png"/>
                                Phần mềm Nhạc
                            </a>
                        </li>
                        <li>
                            <a href="tin-hoc-van-phong.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Statistics-32.png"/>
                                Tin học Văn ph&#242;ng
                            </a>
                        </li>
                        <li>
                            <a href="trinh-doc-email.html">
                                <img src="../img.quantrimang.com/photos/image/icon/email-1.png"/>
                                Tr&#236;nh đọc email
                            </a>
                        </li>
                        <li>
                            <a href="email.html">
                                <img src="../img.quantrimang.com/photos/image/icon/email.png"/>
                                Web Email
                            </a>
                        </li>
                        <li>
                            <a href="luu-tru-chia-se.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Cloud-Checked.png"/>
                                Lưu trữ - Chia sẻ
                            </a>
                        </li>
                        <li>
                            <a href="trinh-duyet.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Browser.png"/>
                                Tr&#236;nh duyệt Web
                            </a>
                        </li>
                        <li>
                            <a href="chinh-sua-anh.html">
                                <img src="../img.quantrimang.com/photos/image/icon/image_edit.png"/>
                                Chỉnh sửa Ảnh
                            </a>
                        </li>
                        <li>
                            <a href="bo-go-tieng-viet.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Font-icon.png"/>
                                Bộ g&#245; tiếng Việt
                            </a>
                        </li>
                        <li>
                            <a href="thiet-ke-do-hoa.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Panorama.png"/>
                                Thiết kế - Đồ họa
                            </a>
                        </li>
                        <li>
                            <a href="nen-va-giai-nen.html">
                                <img src="../img.quantrimang.com/photos/image/icon/compress.png"/>
                                N&#233;n v&#224; Giải n&#233;n
                            </a>
                        </li>
                        <li>
                            <a href="phan-mem-chuyen-doi.html">
                                <img src="../img.quantrimang.com/photos/image/icon/convert-files.png"/>
                                Phần mềm chuyển đổi
                            </a>
                        </li>
                        <li>
                            <a href="ho-tro-download-upload.html">
                                <img src="../img.quantrimang.com/photos/image/icon/up-down.png"/>
                                Hỗ trợ Download - Upload
                            </a>
                        </li>
                        <li>
                            <a href="website-blog.html">
                                <img src="../img.quantrimang.com/photos/image/icon/blog.png"/>
                                Website - Blog
                            </a>
                        </li>
                        <li>
                            <a href="lap-trinh.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Code.png"/>
                                Lập tr&#236;nh
                            </a>
                        </li>
                        <li>
                            <a href="phan-mem-gia-lap.html">
                                <img src="../img.quantrimang.com/photos/image/icon/icon-gia-lap.png"/>
                                Phần mềm giả lập
                            </a>
                        </li>
                        <li>
                            <a href="ban-do-dinh-vi.html">
                                <img src="../img.quantrimang.com/photos/image/icon/map.png"/>
                                Bản đồ &amp; Định vị
                            </a>
                        </li>
                        <li>
                            <a href="chinh-sua-video.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Video-Edit.png"/>
                                Chỉnh sửa Video
                            </a>
                        </li>
                        <li>
                            <a href="thanh-toan-online.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Money.png"/>
                                Thanh to&#225;n Online
                            </a>
                        </li>
                        <li>
                            <a href="cai-dat-go-bo.html">
                                <img src="../img.quantrimang.com/photos/image/icon/uninstall-icon.png"/>
                                C&#224;i đặt - Gỡ bỏ
                            </a>
                        </li>
                        <li>
                            <a href="free-license.html">
                                <img src="../img.quantrimang.com/photos/image/icon/icon-giam-gia.png"/>
                                Miễn ph&#237; - Giảm gi&#225;
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-he-thong  hassub">
                    <a href="he-thong.html">
                        <img src="../img.quantrimang.com/photos/image/icon/icon-he-thong.png"/>
                        Hệ thống
                    </a>
                    <ul>
                        <li>
                            <a href="windows-10-os.html">
                                <img src="../img.quantrimang.com/photos/image/icon/windows.png"/>
                                Windows 10
                            </a>
                        </li>
                        <li>
                            <a href="windows-8-os.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Windows8.png"/>
                                Windows 8
                            </a>
                        </li>
                        <li>
                            <a href="windows-7-os.html">
                                <img src="../img.quantrimang.com/photos/image/icon/windows7.png"/>
                                Windows 7
                            </a>
                        </li>
                        <li>
                            <a href="windows-xp.html">
                                <img src="../img.quantrimang.com/photos/image/icon/windows_xp.png"/>
                                Windows XP
                            </a>
                        </li>
                        <li>
                            <a href="ghost-cai-dat-windows.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Windows-Client.png"/>
                                Ghost - C&#224;i Win
                            </a>
                        </li>
                        <li>
                            <a href="sua-loi-may-tinh.html">
                                <img src="../img.quantrimang.com/photos/image/icon/System-Report.png"/>
                                Sửa lỗi m&#225;y t&#237;nh
                            </a>
                        </li>
                        <li>
                            <a href="giaiphapbaomat.html">
                                <img src="../img.quantrimang.com/photos/image/icon/security.png"/>
                                Giải ph&#225;p bảo mật
                            </a>
                        </li>
                        <li>
                            <a href="diet-virus-spyware.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Hacking.png"/>
                                Diệt Virus - Spyware
                            </a>
                        </li>
                        <li>
                            <a href="bao-mat-may-tinh.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Private.png"/>
                                Bảo mật m&#225;y t&#237;nh
                            </a>
                        </li>
                        <li>
                            <a href="lan-wan.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Network.png"/>
                                Mạng LAN - WAN
                            </a>
                        </li>
                        <li>
                            <a href="cau-hinh-router-switch.html">
                                <img src="../img.quantrimang.com/photos/image/icon/wireless-router.png"/>
                                Cấu h&#236;nh Router/Switch
                            </a>
                        </li>
                        <li>
                            <a href="may-chu.html">
                                <img src="../img.quantrimang.com/photos/image/icon/NAS.png"/>
                                M&#225;y chủ
                            </a>
                        </li>
                        <li>
                            <a href="mail-server.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Group-Message.png"/>
                                Mail Server
                            </a>
                        </li>
                        <li>
                            <a href="thu-thuat-wifi.html">
                                <img src="../img.quantrimang.com/photos/image/icon/icon-wifi.png"/>
                                Thủ thuật Wifi
                            </a>
                        </li>
                        <li>
                            <a href="tang-toc-may-tinh.html">
                                <img src="../img.quantrimang.com/photos/image/icon/faster-computer.png"/>
                                Tăng tốc m&#225;y t&#237;nh
                            </a>
                        </li>
                        <li>
                            <a href="linux-os.html">
                                <img src="../img.quantrimang.com/photos/image/icon/linux-os.png"/>
                                Linux
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-game-tro-choi  hassub">
                    <a href="game-tro-choi.html">
                        <img src="../img.quantrimang.com/photos/image/icon/Controller.png"/>
                        Game - Tr&#242; chơi
                    </a>
                    <ul>
                        <li>
                            <a href="pokemon-go.html">
                                <img src="../img.quantrimang.com/photos/image/icon/pokemon-go-icon.png"/>
                                Pokemon GO
                            </a>
                        </li>
                        <li>
                            <a href="game-mobile.html">
                                <img src="../img.quantrimang.com/photos/image/icon/mobile-game.png"/>
                                Game Mobile
                            </a>
                        </li>
                        <li>
                            <a href="choi-game-online.html">
                                <img src="../img.quantrimang.com/photos/image/icon/online-games.png"/>
                                Game Online
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-ios  hassub">
                    <a href="ios.html">
                        <img src="../img.quantrimang.com/photos/image/icon/apple.png"/>
                        iPhone / iPad
                    </a>
                    <ul>
                        <li>
                            <a href="thiet-lap-co-ban-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Settings-mobile.png"/>
                                Thiết lập cơ bản
                            </a>
                        </li>
                        <li>
                            <a href="du-lieu-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/MicroSD.png"/>
                                Dữ liệu
                            </a>
                        </li>
                        <li>
                            <a href="thu-thuat-ung-dung-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/mobile-app.png"/>
                                Thủ thuật ứng dụng
                            </a>
                        </li>
                        <li>
                            <a href="chat-goi-dien-nhan-tin-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/messages-ios.png"/>
                                Chat - Gọi điện - Nhắn tin
                            </a>
                        </li>
                        <li>
                            <a href="mang-xa-hoi-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/social-ios.png"/>
                                Mạng x&#227; hội
                            </a>
                        </li>
                        <li>
                            <a href="chup-va-xu-ly-anh-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/camera-ios.png"/>
                                Chụp v&#224; xử l&#253; ảnh
                            </a>
                        </li>
                        <li>
                            <a href="quan-ly-chinh-sua-video-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/video-ios.png"/>
                                Quản l&#253; &amp; chỉnh sửa Video
                            </a>
                        </li>
                        <li>
                            <a href="trinh-duyet-add-on-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/browser-ios.png"/>
                                Tr&#236;nh duyệt &amp; Add-on
                            </a>
                        </li>
                        <li>
                            <a href="bao-mat-diet-virus-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/security-ios.png"/>
                                Bảo mật &amp; Diệt virus
                            </a>
                        </li>
                        <li>
                            <a href="luu-tru-dong-bo-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/sync-ios.png"/>
                                Lưu trữ - Đồng bộ
                            </a>
                        </li>
                        <li>
                            <a href="ca-nhan-hoa-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/personal-ios.png"/>
                                C&#225; nh&#226;n h&#243;a
                            </a>
                        </li>
                        <li>
                            <a href="hinh-nen-nhac-chuong-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/ringtones-ios.png"/>
                                H&#236;nh nền &amp; Nhạc chu&#244;ng
                            </a>
                        </li>
                        <li>
                            <a href="ban-do-dinh-vi-ios.html">
                                <img src="../img.quantrimang.com/photos/image/icon/maps-ios.png"/>
                                Bản đồ &amp; Định vị
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-android  hassub">
                    <a href="android.html">
                        <img src="../img.quantrimang.com/photos/image/icon/android.png"/>
                        Android
                    </a>
                    <ul>
                        <li>
                            <a href="thiet-lap-co-ban.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Settings-mobile.png"/>
                                Thiết lập cơ bản
                            </a>
                        </li>
                        <li>
                            <a href="du-lieu.html">
                                <img src="../img.quantrimang.com/photos/image/icon/MicroSD.png"/>
                                Dữ liệu
                            </a>
                        </li>
                        <li>
                            <a href="thu-thuat-ung-dung.html">
                                <img src="../img.quantrimang.com/photos/image/icon/mobile-app.png"/>
                                Thủ thuật ứng dụng
                            </a>
                        </li>
                        <li>
                            <a href="chat-goi-dien-nhan-tin-android.html">
                                <img src="../img.quantrimang.com/photos/image/icon/nhan-tin-android.png"/>
                                Chat - Gọi điện - Nhắn tin
                            </a>
                        </li>
                        <li>
                            <a href="mang-xa-hoi-android.html">
                                <img src="../img.quantrimang.com/photos/image/2015/09/23/social-android.png"/>
                                Mạng x&#227; hội
                            </a>
                        </li>
                        <li>
                            <a href="chup-va-xu-ly-anh-android.html">
                                <img src="../img.quantrimang.com/photos/image/icon/camera-android.png"/>
                                Chụp &amp; Xử l&#253; ảnh
                            </a>
                        </li>
                        <li>
                            <a href="quan-ly-chinh-sua-video-android.html">
                                <img src="../img.quantrimang.com/photos/image/icon/video-android.png"/>
                                Quản l&#253; &amp; Chỉnh sửa Video
                            </a>
                        </li>
                        <li>
                            <a href="trinh-duyet-add-on-android.html">
                                <img src="../img.quantrimang.com/photos/image/icon/browser-android.png"/>
                                Tr&#236;nh duyệt &amp; Add-on
                            </a>
                        </li>
                        <li>
                            <a href="bao-mat-diet-virus-android.html">
                                <img src="../img.quantrimang.com/photos/image/icon/security-android.png"/>
                                Bảo mật &amp; Diệt Virus
                            </a>
                        </li>
                        <li>
                            <a href="luu-tru-dong-bo-android.html">
                                <img src="../img.quantrimang.com/photos/image/icon/sync-android.png"/>
                                Lưu trữ - Đồng bộ
                            </a>
                        </li>
                        <li>
                            <a href="ca-nhan-hoa-android.html">
                                <img src="../img.quantrimang.com/photos/image/icon/personal-android.png"/>
                                C&#225; nh&#226;n h&#243;a
                            </a>
                        </li>
                        <li>
                            <a href="hinh-nen-nhac-chuong-android.html">
                                <img src="../img.quantrimang.com/photos/image/icon/ringtone-android.png"/>
                                H&#236;nh nền &amp; Nhạc chu&#244;ng
                            </a>
                        </li>
                        <li>
                            <a href="ban-do-dinh-vi-android.html">
                                <img src="../img.quantrimang.com/photos/image/icon/maps-android.png"/>
                                Bản đồ &amp; Định vị
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-windows-phone  hassub">
                    <a href="windows-phone.html">
                        <img src="../img.quantrimang.com/photos/image/icon/windows-phone-icon.png"/>
                        Windows Phone
                    </a>
                    <ul>
                        <li>
                            <a href="thiet-lap-co-ban-wp.html">
                                <img src="../img.quantrimang.com/photos/image/icon/settings-windows-phone.png"/>
                                Thiết lập cơ bản
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-mac-os-x  hassub">
                    <a href="mac-os-x.html">
                        <img src="../img.quantrimang.com/photos/image/icon/mac-os-x.png"/>
                        Mac OS X
                    </a>
                    <ul>
                        <li>
                            <a href="bao-mat-mac.html">
                                <img src="../img.quantrimang.com/photos/image/icon/bao-mat-mac.png"/>
                                Bảo mật
                            </a>
                        </li>
                        <li>
                            <a href="ung-dung-van-phong-mac.html">
                                <img src="../img.quantrimang.com/photos/image/icon/office-ios.png"/>
                                Ứng dụng văn ph&#242;ng
                            </a>
                        </li>
                        <li>
                            <a href="quan-ly-email-mac.html">
                                <img src="../img.quantrimang.com/photos/image/icon/mail-mac.png"/>
                                Quản l&#253; Email
                            </a>
                        </li>
                        <li>
                            <a href="phan-mem-he-thong-mac.html">
                                <img src="../img.quantrimang.com/photos/image/icon/system.png"/>
                                Phần mềm hệ thống
                            </a>
                        </li>
                        <li>
                            <a href="du-lieu-file-mac.html">
                                <img src="../img.quantrimang.com/photos/image/icon/folder-mac.png"/>
                                Dữ liệu - File
                            </a>
                        </li>
                        <li>
                            <a href="phan-cung-mac.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Mac-Client.png"/>
                                Phần cứng Mac
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-may-anh-may-quay  ">
                    <a href="may-anh-may-quay.html">
                        <img src="../img.quantrimang.com/photos/image/icon/SLR-64.png"/>
                        Chụp ảnh - Quay phim
                    </a>
                </li>
                <li class="tax-phan-cung  hassub">
                    <a href="phan-cung.html">
                        <img src="../img.quantrimang.com/photos/image/icon/workstation.png"/>
                        Phần cứng
                    </a>
                    <ul>
                        <li>
                            <a href="tu-van-mua-may.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Computer.png"/>
                                Tư vấn mua m&#225;y
                            </a>
                        </li>
                        <li>
                            <a href="may-pc.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Workstation-pc.png"/>
                                Phần cứng PC
                            </a>
                        </li>
                        <li>
                            <a href="laptop.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Notebook-32.png"/>
                                Phần cứng Laptop
                            </a>
                        </li>
                        <li>
                            <a href="may-in.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Print.png"/>
                                M&#225;y in
                            </a>
                        </li>
                        <li>
                            <a href="usb-o-flash.html">
                                <img src="../img.quantrimang.com/photos/image/icon/USB-Connected.png"/>
                                USB - Ổ Flash
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-thu-thuat-seo  ">
                    <a href="thu-thuat-seo.html">
                        <img src="../img.quantrimang.com/photos/image/icon/icon-seo.png"/>
                        Thủ thuật SEO
                    </a>
                </li>
                <li class="tax-kien-thuc-co-ban  ">
                    <a href="kien-thuc-co-ban.html">
                        <img src="../img.quantrimang.com/photos/image/icon/icon-kien-thuc-co-ban.png"/>
                        Kiến thức cơ bản
                    </a>
                </li>
            </ul>
        </li>
        <li class="tax-khoa-hoc">
            <a href="khoa-hoc.html">
                <img src="../img.quantrimang.com/photos/image/icon/Physics-64.png"/>
                Khoa học
            </a>
            <ul>
                <li class="tax-thi-nghiem-khoa-hoc  ">
                    <a href="thi-nghiem-khoa-hoc.html">
                        <img src="../img.quantrimang.com/photos/image/icon/khoahoc/TestTube.png"/>
                        Khoa học vui
                    </a>
                </li>
                <li class="tax-kham-pha-khoa-hoc  ">
                    <a href="kham-pha-khoa-hoc.html">
                        <img src="../img.quantrimang.com/photos/image/icon/khoahoc/earth.png"/>
                        Kh&#225;m ph&#225; khoa học
                    </a>
                </li>
                <li class="tax-bi-an-chuyen-la  ">
                    <a href="bi-an-chuyen-la.html">
                        <img src="../img.quantrimang.com/photos/image/icon/khoahoc/Martian.png"/>
                        B&#237; ẩn - Chuyện lạ
                    </a>
                </li>
                <li class="tax-suc-khoe  hassub">
                    <a href="suc-khoe.html">
                        <img src="../img.quantrimang.com/photos/image/icon/Health.png"/>
                        Chăm s&#243;c Sức khỏe
                    </a>
                    <ul>
                        <li>
                            <a href="suc-khoe-gia-dinh.html">
                                <img src="../img.quantrimang.com/photos/image/icon/UNHCR-64.png"/>
                                Sức khỏe gia đ&#236;nh
                            </a>
                        </li>
                        <li>
                            <a href="bi-quyet-song-vui.html">
                                <img src="../img.quantrimang.com/photos/image/icon/LOL-64.png"/>
                                B&#237; quyết Sống vui
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-khoa-hoc-vu-tru  ">
                    <a href="khoa-hoc-vu-tru.html">
                        <img src="../img.quantrimang.com/photos/image/icon/khoahoc/WaxingCrescent.png"/>
                        Khoa học Vũ trụ
                    </a>
                </li>
                <li class="tax-kham-pha-thien-nhien  hassub">
                    <a href="kham-pha-thien-nhien.html">
                        <img src="../img.quantrimang.com/photos/image/icon/khoahoc/NaturalFood.png"/>
                        Kh&#225;m ph&#225; thi&#234;n nhi&#234;n
                    </a>
                    <ul>
                        <li>
                            <a href="the-gioi-dong-vat.html">
                                <img src="../img.quantrimang.com/photos/image/icon/khoahoc/Hummingbird.png"/>
                                Thế giới động vật
                            </a>
                        </li>
                        <li>
                            <a href="dai-duong-hoc.html">
                                <img src="../img.quantrimang.com/photos/image/icon/khoahoc/Dolphin.png"/>
                                Đại dương học
                            </a>
                        </li>
                        <li>
                            <a href="the-gioi-thuc-vat.html">
                                <img src="../img.quantrimang.com/photos/image/icon/khoahoc/Sprout.png"/>
                                Thế giới thực vật
                            </a>
                        </li>
                        <li>
                            <a href="khi-hau-thoi-tiet.html">
                                <img src="../img.quantrimang.com/photos/image/icon/khoahoc/Storm.png"/>
                                Kh&#237; hậu - Thời tiết
                            </a>
                        </li>
                        <li>
                            <a href="bao-ve-thien-nhien.html">
                                <img src="../img.quantrimang.com/photos/image/icon/khoahoc/Greentech.png"/>
                                Bảo vệ thi&#234;n nhi&#234;n
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-moi-truong  ">
                    <a href="moi-truong.html">
                        <img src="../img.quantrimang.com/photos/image/icon/moi-truong-icon-32.png"/>
                        M&#244;i trường
                    </a>
                </li>
                <li class="tax-y-hoc  hassub">
                    <a href="y-hoc.html">
                        <img src="../img.quantrimang.com/photos/image/icon/khoahoc/hospital.png"/>
                        Y học
                    </a>
                    <ul>
                        <li>
                            <a href="benh-cum.html">
                                <img src="../img.quantrimang.com/photos/image/icon/khoahoc/virus.png"/>
                                Bệnh c&#250;m
                            </a>
                        </li>
                        <li>
                            <a href="benh-ung-thu.html">
                                <img src="../img.quantrimang.com/photos/image/icon/khoahoc/Cancer.png"/>
                                Bệnh ung thư
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-khao-co-hoc  ">
                    <a href="khao-co-hoc.html">
                        <img src="../img.quantrimang.com/photos/image/icon/khoahoc/pharaoh.png"/>
                        Khảo cổ học
                    </a>
                </li>
                <li class="tax-phat-minh-khoa-hoc  hassub">
                    <a href="phat-minh-khoa-hoc.html">
                        <img src="../img.quantrimang.com/photos/image/icon/khoahoc/idea.png"/>
                        Ph&#225;t minh khoa học
                    </a>
                    <ul>
                        <li>
                            <a href="phat-minh-the-gioi.html">
                                <img src="../img.quantrimang.com/photos/image/icon/khoahoc/idea1.png"/>
                                Thế giới
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-cau-chuyen-khoa-hoc  ">
                    <a href="cau-chuyen-khoa-hoc.html">
                        <img src="../img.quantrimang.com/photos/image/icon/khoahoc/Einstein.png"/>
                        C&#226;u chuyện Khoa học
                    </a>
                </li>
                <li class="tax-anh-dep-khoa-hoc  ">
                    <a href="anh-dep-khoa-hoc.html">
                        <img src="../img.quantrimang.com/photos/image/icon/khoahoc/Image.png"/>
                        Ảnh đẹp Khoa học
                    </a>
                </li>
            </ul>
        </li>
        <li class="tax-dien-may">
            <a href="dien-may.html">
                <img src="../img.quantrimang.com/photos/image/icon/Fridge.png"/>
                Điện m&#225;y
            </a>
            <ul>
                <li class="tax-tu-lanh  ">
                    <a href="tu-lanh.html">
                        <img src="../img.quantrimang.com/photos/image/icon/Fridge-64.png"/>
                        Tủ lạnh
                    </a>
                </li>
                <li class="tax-tivi  hassub">
                    <a href="tivi.html">
                        <img src="../img.quantrimang.com/photos/image/icon/icon-tv.png"/>
                        Tivi
                    </a>
                    <ul>
                        <li>
                            <a href="smart-tivi.html">
                                <img src="../img.quantrimang.com/photos/image/icon/smart-tv.png"/>
                                Smart Tivi
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-dieu-hoa  ">
                    <a href="dieu-hoa.html">
                        <img src="../img.quantrimang.com/photos/image/icon/AirConditioner.png"/>
                        Điều h&#242;a
                    </a>
                </li>
                <li class="tax-may-giat  ">
                    <a href="may-giat.html">
                        <img src="../img.quantrimang.com/photos/image/icon/WashingMachine.png"/>
                        M&#225;y giặt
                    </a>
                </li>
                <li class="tax-quat-cac-loai  ">
                    <a href="quat-cac-loai.html">
                        <img src="../img.quantrimang.com/photos/image/icon/Fan.png"/>
                        Quạt c&#225;c loại
                    </a>
                </li>
            </ul>
        </li>
        <li class="tax-cuoc-song">
            <a href="cuoc-song.html">
                <img src="../img.quantrimang.com/photos/image/icon/LifeCycle.png"/>
                Cuộc sống
            </a>
            <ul>
                <li class="tax-ky-nang  hassub">
                    <a href="ky-nang.html">
                        <img src="../img.quantrimang.com/photos/image/icon/Training.png"/>
                        Kỹ năng
                    </a>
                    <ul>
                        <li>
                            <a href="ky-nang-song.html">
                                <img src="../img.quantrimang.com/photos/image/icon/life-icon.png"/>
                                Kỹ năng sống
                            </a>
                        </li>
                        <li>
                            <a href="ky-nang-cong-viec.html">
                                <img src="../img.quantrimang.com/photos/image/icon/work-icon.png"/>
                                Kỹ năng C&#244;ng việc
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-am-thuc  hassub">
                    <a href="am-thuc.html">
                        <img src="../img.quantrimang.com/photos/image/icon/Food-Wine.png"/>
                        Ẩm thực
                    </a>
                    <ul>
                        <li>
                            <a href="an-uong-dinh-duong.html">
                                <img src="../img.quantrimang.com/photos/image/icon/Food.png"/>
                                Ăn uống dinh dưỡng
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tax-lam-dep  ">
                    <a href="lam-dep.html">
                        <img src="../img.quantrimang.com/photos/image/icon/PortraitMode.png"/>
                        L&#224;m đẹp
                    </a>
                </li>
                <li class="tax-nuoi-day-con  ">
                    <a href="nuoi-day-con.html">
                        <img src="../img.quantrimang.com/photos/image/icon/Breastfeeding.png"/>
                        Nu&#244;i dạy con
                    </a>
                </li>
                <li class="tax-nha-cua  ">
                    <a href="nha-cua.html">
                        <img src="../img.quantrimang.com/photos/image/icon/Caretaker-64.png"/>
                        Chăm s&#243;c Nh&#224; cửa
                    </a>
                </li>
                <li class="tax-kinh-nghiem-du-lich  ">
                    <a href="kinh-nghiem-du-lich.html">
                        <img src="../img.quantrimang.com/photos/image/icon/World-Map.png"/>
                        Kinh nghiệm Du lịch
                    </a>
                </li>
                <li class="tax-diy-handmade  ">
                    <a href="diy-handmade.html">
                        <img src="../img.quantrimang.com/photos/image/icon/GardenGloves.png"/>
                        DIY - Handmade
                    </a>
                </li>
                <li class="tax-tet-trung-thu  ">
                    <a href="tet-trung-thu.html">
                        <img src="../img.quantrimang.com/photos/image/icon/tet-trung-thu-icon.png"/>
                        Tết Trung thu
                    </a>
                </li>
                <li class="tax-cuoi-hoi  ">
                    <a href="cuoi-hoi.html">
                        <img src="../img.quantrimang.com/photos/image/icon/Wedding.png"/>
                        Cưới hỏi
                    </a>
                </li>
                <li class="tax-halloween  ">
                    <a href="halloween.html">
                        <img src="../img.quantrimang.com/photos/image/icon/halloween-32.png"/>
                        Halloween
                    </a>
                </li>
                <li class="tax-meo-vat  ">
                    <a href="meo-vat.html">
                        <img src="../img.quantrimang.com/photos/image/icon/meo-vat-32.png"/>
                        Mẹo vặt
                    </a>
                </li>
                <li class="tax-giang-sinh-noel  ">
                    <a href="giang-sinh-noel.html">
                        <img src="../img.quantrimang.com/photos/image/icon/wreath.png"/>
                        Gi&#225;ng sinh - Noel
                    </a>
                </li>
                <li class="tax-tet  ">
                    <a href="tet.html">
                        <img src="../img.quantrimang.com/photos/image/icon/Tet-icon.png"/>
                        Tết 2017
                    </a>
                </li>
                <li class="tax-valentine  ">
                    <a href="valentine.html">
                        <img src="../img.quantrimang.com/photos/image/icon/valentine-icon.png"/>
                        Valentine 2017
                    </a>
                </li>
            </ul>
        </li>
        <li class="tax-video">
            <a href="video.html">
                <img src="../img.quantrimang.com/photos/image/icon/Video.png"/>
                Video
            </a>
            <ul>
                <li class="tax-video-huong-dan  ">
                    <a href="video-huong-dan.html">
                        <img src="../img.quantrimang.com/photos/image/icon/technology.png"/>
                        C&#244;ng nghệ
                    </a>
                </li>
                <li class="tax-cisco-lab  ">
                    <a href="cisco-lab.html">
                        <img src="../img.quantrimang.com/photos/image/icon/Cisco.png"/>
                        Cisco Lab
                    </a>
                </li>
                <li class="tax-microsoft-lab  ">
                    <a href="microsoft-lab.html">
                        <img src="../img.quantrimang.com/photos/image/icon/RunCommand.png"/>
                        Microsoft Lab
                    </a>
                </li>
                <li class="tax-video-khoa-hoc  ">
                    <a href="video-khoa-hoc.html">
                        <img src="../img.quantrimang.com/photos/image/icon/khoahoc/VideoPlaylist.png"/>
                        Video Khoa học
                    </a>
                </li>
            </ul>
        </li>
        <li class="tax-tong-hop">
            <a href="tong-hop.html">
                <img src="../img.quantrimang.com/photos/image/icon/News.png"/>
                Tổng hợp
            </a>
        </li>
    </ul>
</div>
