<?php
$arr_content_hot = unserialize(ARR_CONTENT_HOT_LIST);
?>

<div id="adrighttop" class="adbox">
    <!-- 300x250-->
    <img src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/300x250.jpg'; ?>">
</div>

<div class="top-news">
    <div class="title-top-news">Được xem nhiều</div>
    <ul>
        <?php foreach ($arr_content_hot as $content): ?>
        <li class="item-top">
            <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content['cont_slug'], 'contentId' => $arr_content['cont_id']]) ?>">
                <img src="<?php echo $arr_content['cont_main_image'] ?>"
                     alt="<?php echo $arr_content['cont_title'] ?>"/>
                <?php echo $arr_content['cont_title'] ?>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
</div>


<div id="mrc311" class="adbox" data-realclickzone="311"></div>

<div class="sticky">
    <div class="adbox fbbox">
        <div class="fb-page" data-href="https://www.facebook.com/quantrimang.com.vn" data-small-header="true"
             data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"></div>
        <div class="fbhd">Thích trang để theo dõi trên <a href="https://www.facebook.com/quantrimang.com.vn"
                                                          target="_blank" rel="nofollow">Facebook</a></div>
    </div>
    <div id="adrightsecond" class="adbox" data-realclickzone="306"></div>
</div>
