<div class="td-crumb-container">
    <div class="entry-crumbs">
        <span>
            <a title="Home" class="entry-crumb" itemprop="url"
               href="<?php echo $this->serverUrl() . $this->Url('home') ?>">
                <span itemprop="title"><i class="fa fa-home"></i> Home</span>
            </a>
        </span>
        <i class="td-icon-right td-bread-sep"></i>
        <span class=td-bred-no-url-last>
            Contact
        </span>
    </div>
</div>
<div class="td-ss-main-content">
<div class="td-page-header">
    <h1 class="entry-title td-page-title">
        <span>Contact</span>
    </h1>
</div>
<div class="vc_column-inner ">
    <div class="wpb_wrapper">
        <div class="wpb_text_column wpb_content_element ">
            <div class="wpb_wrapper">
                <p>You are a part of the Rebel Alliance and a traitor so what do you think of her Han.
                    But with the blast shield down even see! How am I supposed to fight need your help
                    Luke. She needs your help getting too old for this sort of thing.</p>
                <p>Act so surprised your highness. You mercy mission this time several transmissions
                    were beamed to this ship by Rebel spies.</p>
                <ul>
                    <li>You mean it controls your actions?</li>
                    <li>But with the blast shield down can even see! How am I supposed to fight?</li>
                    <li>I get involved got work to do not that I like the Empire</li>
                    <li>But nothing can do about it right now such a long way from here.</li>
                </ul>
            </div>
        </div>
        <div class="vc_row wpb_row vc_inner td-pb-row">
            <div class="wpb_column vc_column_container td-pb-span6">
                <div class="vc_column-inner ">
                    <div class="wpb_wrapper">
                        <div
                            class="td_block_wrap td_block_text_with_title td_uid_16_581be09a3f447_rand td-pb-border-top"
                            data-td-block-uid="td_uid_16_581be09a3f447"><h4 class="block-title"><span>Contact Details</span>
                            </h4>
                            <div class="td_mod_wrap"><strong>Newspaper Web Service</strong><br>
                                123 Đinh Tien Hoang, Q1, TPHCM<p></p>
                                <p>(+84) 96 207 3217  (main number)<br>
                                    ncongphuoc (skype)</p>
                                <p>Email: <strong><a href="mailto:contact@newspaper.com"
                                                     target="_blank">tintuc360@gmail.com</a></strong>
                                </p></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="wpb_column vc_column_container td-pb-span6">
                <div class="vc_column-inner ">
                    <div class="wpb_wrapper">
                        <div
                            class="td_block_wrap td_block_text_with_title td_uid_17_581be09a3f6f4_rand td-pb-border-top"
                            data-td-block-uid="td_uid_17_581be09a3f6f4"><h4 class="block-title"><span>About us</span>
                            </h4>
                            <div class="td_mod_wrap"><strong>Newspaper</strong> is your news
                                entertainment music fashion website. We provide you with the latest
                                breaking news and videos straight from entertainment industry world.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="vc_row wpb_row vc_inner td-pb-row">
            <div class="wpb_column vc_column_container td-pb-span12">
                <div class="vc_column-inner ">
                    <div class="wpb_wrapper">
                        <div class="wpb_raw_code wpb_content_element wpb_raw_html">
                            <div class="wpb_wrapper">
                                <h4 class="block-title"><span>Send us a message!</span></h4>
                            </div>
                        </div>
                        <div role="form"lang="vi-VN">
                            <div class="screen-reader-response"></div>
                            <div action="#" method="post"
                                  class="wpcf7-form" novalidate="novalidate">
                                <p><span class="wpcf7-form-control-wrap your-name"><input type="text"
                                                                                          name="your-name"
                                                                                          value="Name"
                                                                                          size="40"
                                                                                          class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required"
                                                                                          aria-required="true"
                                                                                          aria-invalid="false"></span>
                                </p>
                                <p><span class="wpcf7-form-control-wrap your-email"><input type="email"
                                                                                           name="your-email"
                                                                                           value="Email"
                                                                                           size="40"
                                                                                           class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                                                                           aria-required="true"
                                                                                           aria-invalid="false"></span>
                                </p>
                                <p><span class="wpcf7-form-control-wrap your-subject"><input type="text"
                                                                                             name="your-subject"
                                                                                             value="Website"
                                                                                             size="40"
                                                                                             class="wpcf7-form-control wpcf7-text"
                                                                                             aria-invalid="false"></span>
                                </p>
                                <p><span class="wpcf7-form-control-wrap your-message"><textarea
                                            name="your-message" cols="40" rows="10"
                                            class="wpcf7-form-control wpcf7-textarea"
                                            aria-invalid="false">Your Message</textarea></span></p>
                                <p><input type="submit" value="Send"
                                          class="wpcf7-form-control wpcf7-submit"><img
                                        class="ajax-loader"
                                        alt="Sending ..." style="visibility: hidden;"></p>
                                <div class="wpcf7-response-output wpcf7-display-none"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>